name: flutter_json_view
description: Displaying json models in a Flutter widget with customization.
version: 1.1.0
homepage: https://github.com/Frezyx/flutter_json_view

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter